python train.py -c configs/nesterov_higgs.yaml
python train.py -c configs/nesterov_susy.yaml
python train.py -c configs/nesterov_syn8.yaml
python train.py -c configs/nesterov_syn8.yaml
python train.py -c configs/highway_cd1.yaml
python train.py -c configs/highway_cd2.yaml
python train.py -c configs/highway_higgs.yaml
python train.py -c configs/highway_susy.yaml
python train.py -c configs/highway_syn8.yaml